version: '3'
services:
  web:
    build: .
    command: mix phoenix.server
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    ports:
      - 4000:4000
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your-urls-ex
  redis:
    image: redis:3.2-alpine
