version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - app
    ports:
      - 80:80
  app:
    build: .
    command: mix phoenix.server
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    environment:
     HOST: jobsco.re
     DB_USER: postgres
     DB_PASS: password
     DB_HOST: db
     DB_NAME: your-urls-ex
     REDIS_HOST: redis
     AUTHORIZATION_TOKEN_SALT: YourUrlTokenSalt
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your-urls-ex
  redis:
    image: redis:3.2-alpine
